git-ci: use strict mode
Terminate when a command returns a non-zero exit code.

diff --git a/git-ci b/git-ci
--- a/git-ci
+++ b/git-ci
@@ -11,6 +11,10 @@ _yellow="\e[1;33m"
 _blue="\e[1;34m"
 _strong="\e[1;39m"
 
+# terminate when a command returns a non-zero exit code 
+# note: '||:' at the end of a pipe mask a non-zero exit
+set -e
+
 # Main
 # change dir to inputted path if valid
 if [ -d "$1" ]; then
