feat(git-ci): improve logging

diff --git a/git-ci b/git-ci
--- a/git-ci
+++ b/git-ci
@@ -1,15 +1,42 @@
 #!/bin/sh
-# Pull and push on a Git repository but only if it has a valid remote and state is clean.
-# This does a job similar to git sync but is more suitable for automated envs.
+# Pull and push on a Git repository but only if it makes sense.
+# This does a job similar to git sync but smarter and more suitable for automated envs.
 
 # usage: git-sync <path-to-parent-dir> (optional)
 
-# Utils
-# text formatting 
-_reset="\e[0;0m"
-_yellow="\e[1;33m"
-_blue="\e[1;34m"
-_strong="\e[1;39m"
+# Logging 
+# shellcheck disable=2059
+
+# is it running under systemd?
+if [ "$TERM" = "dumb" ]; then
+  _log_emerg="<0>%s\n" # red
+  _log_alert="<1>%s\n"
+  _log_crit="<2>%s\n"
+  _log_error="<3>%s\n"
+  _log_warning="<4>%s\n" # yellow
+  _log_notice="<5>%s\n" # white
+  _log_info="<6>%s\n"
+  _log_debug="<7>%s\n" # muted 
+
+else
+  # formatting escape codes
+  _fmt_clear="\e[0;0m"
+  _fmt_bold="\e[1;0m"
+  _fmt_red="\e[1;31m"
+  _fmt_yellow="\e[1;33m"
+  _fmt_blue="\e[1;34m"
+  _fmt_gray="\e[1;30m"
+
+  # log levels strings (systemd convention)
+  _log_emerg="${_fmt_red}EMERGENCY: %s${_fmt_clear}\n"
+  _log_alert="${_fmt_red}ALERT: %s${_fmt_clear}\n"
+  _log_crit="${_fmt_red}CRITICAL: %s${_fmt_clear}\n"
+  _log_error="${_fmt_red}ERROR: %s${_fmt_clear}\n"
+  _log_warning="${_fmt_yellow}WARNING: %s$_fmt_clear}\n"
+  _log_notice="${_fmt_bold}NOTICE: %s${_fmt_clear}\n"
+  _log_info="${_fmt_clear}INFO: %s\n${_fmt_clear}"
+  _log_debug="${_fmt_gray}DEBUG: %s${_fmt_clear}\n"
+fi
 
 # Main
 # change dir to inputted path if valid
@@ -18,26 +45,29 @@ if [ -d "$1" ]; then
 fi
 
 # get repo name
-path="$(pwd)"
-repo="${path##/*/}"
+_path="$(pwd)"
+_repo_name="${_path##/*/}"
 _repo_root=$(git rev-parse --show-toplevel 2>/dev/null)
 
 # Check before acting
 _check() {
-  # check if repo has remotes
-  [ "$(git remote | wc -l)" = 0 ] && return 1
+  if [ "$(git remote | wc -l)" = 0 ]; then
+    printf "$_log_error" "Repository has no remotes."
+    exit 1
+  fi
 
   # check if repo is in a dirty state
   # NOTE: it may be necessary to run git diff first to ensure the index is up to date
-  git diff --quiet; git diff-index --quiet HEAD -- || return 1
-  return 0
-
-  # TODO: Improve dirty/valid repo detection.
+  if ! git diff --quiet; git diff-index --quiet HEAD -- ; then
+    printf "$_log_error" "Repository is in a dirty state."
+    exit 1
+  fi
 }
 
 # Pull changes
 _pull() {
   if git rev-parse --is-shallow-repository >/dev/null; then
+    printf "$_log_info" "Repository is shallow."
     git pull --ff-only --rebase
   else
     # NOTE: Fetching all is important to fetch upstream commits on forks.
@@ -47,23 +77,31 @@ _pull() {
 
 # Push changes
 _push() {
-  # check if branch is main/master otherwise return 
   _branch=$(git symbolic-ref --short HEAD)
-  ! [ "$_branch" = "main" ] && ! [ "$_branch" = "master" ] && return 1 
+  if ! [ "$_branch" = "main" ] && ! [ "$_branch" = "master" ]; then
+    printf "$_log_warning" "Current branch is not main or master."
+    return 1 
+  fi
 
-  # Check for unpushed commits
-  [ "$(git rev-list HEAD@\{upstream\}..HEAD | wc -l)" = 0 ] && return 1
+  if [ "$(git rev-list HEAD@\{upstream\}..HEAD | wc -l)" = 0 ]; then
+    printf "$_log_info" "No commits to push."
+    return 1
+  fi
 
   # NOTE: Authentication is completely server-side and Git can't know if user
   # is allowed to push. A workaround to prevent pushes is to set 'pushurl' to
   # an invalid value.
 
-  # don't push on gerrit repos.
-  git remote | grep gerrit && return 1
+  if git remote | grep gerrit; then
+    printf "$_log_info" "Gerrit repository. Skip push."
+    return 1
+  fi
 
   git push
 }
 
-printf "${_strong}Working on ${_yellow}%s${_reset}\n" "$repo"
-_check && _pull && _push
-printf "${_strong}Done on ${_blue}%s${_reset}\n\n" "$repo"
+printf "$_log_notice" "Working on '$_repo_name'"
+_check
+_pull
+_push
+printf "$_log_notice" "Done work '$_repo_name'"
